### ISSUE TITLE
invalid data character - fcct fails to generate ignition

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fcct#113]
Using `fcct` on MacOS
```console
$ fcct -V
Fedora CoreOS Config Transpiler 0.6.0
```

If we have a YAML file containing this snippet of code, then ignition file is not generated and fails by stating. (you can ignore the line number warning as it is part of a big file.  Col 17 is "data" - first letter

```console
error at $.storage.files.8.contents.source, line 80 col 17: invalid data character
```

```yaml
storage:
  files:
    - path: /etc/chrony.conf
      overwrite: true
      contents: 
        source: data:text/plain;charset=utf-8,%23%20Add%20AWS%20NTP%20Server%20to%20the%20top%20of%20the%20list%0Aserver%20169.254.169.123%20iburst%20prefer%20minpoll%204%20maxpoll 4%0A%0A%23%20Use%20public%20servers%20from%20the%20pool.ntp.org%20project.%0A%23%20Please%20consider%20joining%20the%20pool%20(http%3A%2F%2Fwww.pool.ntp.org%2Fjoin.html).%0Apool%202.fedora.pool.ntp.org%20iburst%0A%0A%23%20Record%20the%20rate%20at%20which%20the%20system%20clock%20gains%2Flosses%20time.%0Adriftfile%20%2Fvar%2Flib%2Fchrony%2Fdrift%0A%0A%23%20Allow%20the%20system%20clock%20to%20be%20stepped%20in%20the%20first%20three%20updates%0A%23%20if%20its%20offset%20is%20larger%20than%201%20second.%0Amakestep%201.0%203%0A%0A%23%20Enable%20kernel%20synchronization%20of%20the%20real-time%20clock%20(RTC).%0Artcsync%0A%0A%23%20Enable%20hardware%20timestamping%20on%20all%20interfaces%20that%20support%20it.%0A%23hwtimestamp%20*%0A%0A%23%20Increase%20the%20minimum%20number%20of%20selectable%20sources%20required%20to%20adjust%0A%23%20the%20system%20clock.%0A%23minsources%202%0A%0A%23%20Allow%20NTP%20client%20access%20from%20local%20network.%0A%23allow%20192.168.0.0%2F16%0A%0A%23%20Serve%20time%20even%20if%20not%20synchronized%20to%20a%20time%20source.%0A%23local%20stratum%2010%0A%0A%23%20Specify%20file%20containing%20keys%20for%20NTP%20authentication.%0Akeyfile%20%2Fetc%2Fchrony.keys%0A%0A%23%20Get%20TAI-UTC%20offset%20and%20leap%20seconds%20from%20the%20system%20tz%20database.%0Aleapsectz%20right%2FUTC%0A%0A%23%20Specify%20directory%20for%20log%20files.%0Alogdir%20%2Fvar%2Flog%2Fchrony%0A%0A%23%20Select%20which%20information%20is%20logged.%0A%23log%20measurements%20statistics%20tracking%0A
      mode: 0644
```

I have tried use of both `data:text/plain;charset=iso-8859-7,` and `data:text/plain;charset=utf-8,` with the same result.

**Comment by bgilbert** [comment]
> maxpoll 4

The problem is the space character.  If you replace it with `%20`, the sample will transpile successfully.

A couple other notes:
- The content type and charset are ignored.  You can just say `data:,<contents>`.
- For more readability, you can use the `inline` attribute:

```yaml
storage:
  files:
    - path: /etc/chrony.conf
      overwrite: true
      contents: 
        inline: |
          # Add AWS NTP Server to the top of the list
          server 169.254.169.123 iburst prefer minpoll 4 maxpoll 4

          # Use public servers from the pool.ntp.org project.
          # Please consider joining the pool (http://www.pool.ntp.org/join.html).
          pool 2.fedora.pool.ntp.org iburst

          # Record the rate at which the system clock gains/losses time.
          driftfile /var/lib/chrony/drift

          # Allow the system clock to be stepped in the first three updates
          # if its offset is larger than 1 second.
          makestep 1.0 3

          # Enable kernel synchronization of the real-time clock (RTC).
          rtcsync

          # Enable hardware timestamping on all interfaces that support it.
          #hwtimestamp *

          # Increase the minimum number of selectable sources required to adjust
          # the system clock.
          #minsources 2

          # Allow NTP client access from local network.
          #allow 192.168.0.0/16

          # Serve time even if not synchronized to a time source.
          #local stratum 10

          # Specify file containing keys for NTP authentication.
          keyfile /etc/chrony.keys

          # Get TAI-UTC offset and leap seconds from the system tz database.
          leapsectz right/UTC

          # Specify directory for log files.
          logdir /var/log/chrony

          # Select which information is logged.
          #log measurements statistics tracking
      mode: 0644
```
