### ISSUE TITLE
update language in spec about merge + replace

### ISSUE THREAD

**Issue by miabbott** [coreos/fcct#126]
Perhaps it is just me not reading the spec carefully enough, but I made the mistake of trying to merge two FCCT yaml docs like this:

```yaml
variant: fcos
version: 1.1.0
ignition:
  config:
    merge:
      - local: config1.yaml
      - local: config2.yaml
```

Which resulted in an Ignition JSON document that was not parsed correctly by Ignition.  While this was the correct behavior, I think it is easy to make the mistake of seeing `merge` in the spec and trying something like I did.

Would it be possible to update the language in the spec for the `ignition` portion to be clear that `merge` and `replace` expect Ignition JSON documents and not FCCT YAML docs?
