### ISSUE TITLE
Consider supporting 0644 or 644 interchangeably like chmod

### ISSUE THREAD

**Issue by jdoss** [coreos/fcct#131]
When using `chmod` you can use 0644 or 644 interchangeably. The result is the same: 

```
$ ls -lah test.dhall; chmod 0644 test.dhall; ls -lah test.dhall
-rw-r--r--. 1 jdoss jdoss 193 Aug 29 23:28 test.dhall
-rw-r--r--. 1 jdoss jdoss 193 Aug 29 23:28 test.dhall
$ ls -lah test.dhall; chmod 644 test.dhall; ls -lah test.dhall
-rw-r--r--. 1 jdoss jdoss 193 Aug 29 23:28 test.dhall
-rw-r--r--. 1 jdoss jdoss 193 Aug 29 23:28 test.dhall
```
We should consider letting users write modes like this as well. 

```
variant: fcos
version: 1.1.0
storage:
  files:
    - path: /opt/file
      contents:
        inline: Hello, world!
      mode: 644
      user:
        id: 500
      group:
        id: 501
```

If the special bits are not set, just assume it's zero. I ran into this issue when trying to use [Dhall Lang](https://github.com/dhall-lang/dhall-lang) to manage my FCCs and Dhall will strip off leading zeros when you convert YAML to Dhall and then you end up with wonky permissions when you feed your Dhall back into YAML for consumption via FCCT. 

FWIW Dhall is looking into how to handle https://github.com/dhall-lang/dhall-lang/issues/1058#issuecomment-683375211 octal numerals on their end, but I feel that giving the same interchangeable user experience as `chmod` in a FCC would be a nice thing to have.
