### ISSUE TITLE
sugar for provisioning via container

### ISSUE THREAD

**Issue by cgwalters** [coreos/fcct#35]
One thing I think would be interesting is sugar like this:

provisioncontainer: quay.io/myuser/setup@sha256:shashasha

This would expand into a systemd unit which ran podman under `ConditionFirstBoot=yes` something like this:
`podman run --rm quay.io/myuser/setup --privileged -v /:/host`

And we could give some examples of using "first boot containers" like this that can do completely arbitrary things, say use an Ansible playbook pointing at the host, or use Ruby scripts - whatever.

This isn't hard to write manually but it's also not entirely obvious, and we'd be encouraging the pattern of containerization even for early boot.

**Comment by ajeddeloh** [comment]
I think it would be good to make this more general for launching containers in general, though that require adding something like `runtime-args` for things `--volume` and `--privileged`. Maybe something like:
```yaml
containers:
 - image: `quay.io/example/example:v2`
   runtime: docker # docker | podman, podman default. docker adds the correct unit deps for docker.socket
   runtime-args: [ "--net=host" ]
   provisioning: true # adds `--privileged`, `-v /:host` to runtimeargs, ConditionFirstBoot=yes to the unit
   dropins:
     - <systemd drop ins for the unit>
```
This would cut down the boilerplate for units in general basically killing two birds with one stone
