### ISSUE TITLE
Error unmarshaling yaml

### ISSUE THREAD

**Issue by Drakkai** [coreos/fcct#38]
I'm trying to convert FCC like below to Ignition config but getting error:
```
Error translating config: Error unmarshaling yaml: yaml: line 4: mapping values are not allowed in this context
```
My configuration file:
```
variant: fcos
version: 1.0.0
passwd:
  users:
    - name: drakkai
      ssh_authorized_keys:
      - ssh-rsa "<removed>"
      home_dir: /home/drakkai
      groups: 
        - wheel
      shell: /bin/bash
```
I tried fcct in versions 0.2.0 and 0.1.0 on windows and linux with the same error. So I thought that I wrote something wrong in FCC, but getting the same even if I use someone else configuration file. What can it be caused by?
