### ISSUE TITLE
sugar to automatically add mount units for filesystems

### ISSUE THREAD

**Issue by dustymabe** [coreos/fcct#48]
As a user it would be nice to have my systemd mount unit automatically generated for me without having to craft one myself. We could probably craft something that works for most use cases and allow the user to disable autogeneration and provide their own if they want to. 

In my case I was hitting the [nuance](https://unix.stackexchange.com/a/345518) where I named my mount unit `docker.mount` where I needed to name it `var-lib-docker.mount`

I was adapting this example from the docs: https://github.com/coreos/fcct/blob/f9513c5b8e0bf03262bfe1fb3ab8c1ed8e5b55f1/docs/examples.md#filesystems-and-partitions and simply replaced `var.mount` with `docker.mount`.

**Comment by dustymabe** [comment]
>  create_mount_unit: true

👍

**Comment by bgilbert** [comment]
`with_mount_unit` added in FCCT 0.3.0.

**Comment by xenorites** [comment]
```
variant: fcos
version: 1.1.0-experimental
storage:
  filesystems:
    - path: /var/lib/docker
      device: /dev/vda
      format: xfs
      with_mount_unit: true
```

Using the above input for fcct functions as expected when PXE booting coreos. The volume `/dev/vda` is successfully mounted to the specified path: `/var/lib/docker`. Worth noting that virtio volumes can reliably be specified by their `/dev/vd?` name since that can be specified in the VM definition.

**Comment by kelleyk** [comment]
And here's an example of me doing the same thing in an AWS environment (hence the device naming):

```
variant: fcos
version: 1.1.0-experimental  # in order to get `with_mount_unit` option; works with current stable FCCT and FCOS
storage:
  disks:
    - device: "/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol047890a35c50b6f07"
      partitions:
        - number: 1
          start_mib: 1  # 2048 * 512b sectors
  filesystems:
    - path: "/var/srv"  # symlinked to /srv, because this is the OSTree world
      device: "/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol047890a35c50b6f07-part1"
      format: "xfs"
      with_mount_unit: true
```

This creates an `/etc/systemd/system/var-srv.mount` containing

```
# Generated by FCCT
[Unit]
Before=local-fs.target
Requires=systemd-fsck@/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol047890a35c50b6f07-part1
After=systemd-fsck@/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol047890a35c50b6f07-part1

[Mount]
Where=/var/srv
What=/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol047890a35c50b6f07-part1
Type=xfs

[Install]
RequiredBy=local-fs.target[
```

... which is slightly different than what the FCCT configuration documentation (for 1.0.0) suggests that you manually create.  The unit above (automatically created by the `with_mount_unit: true` option) works nicely, whereas the one suggested by the documentation causes a boot failure because the ordering directives are missing.

**Comment by kelleyk** [comment]
And here's an example of me doing the same thing in an AWS environment (hence the stable naming):

```
variant: fcos
version: 1.1.0-experimental  # in order to get `with_mount_unit` option; works with current stable FCCT and FCOS
storage:
  disks:
    - device: "/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol047890a35c50b6f07"
      partitions:
        - number: 1
          start_mib: 1  # 2048 * 512b sectors
  filesystems:
    - path: "/var/srv"  # symlinked to /srv, because this is the OSTree world
      device: "/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol047890a35c50b6f07-part1"
      format: "xfs"
      with_mount_unit: true
```

This creates an `/etc/systemd/system/var-srv.mount` containing

```
# Generated by FCCT
[Unit]
Before=local-fs.target
Requires=systemd-fsck@/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol047890a35c50b6f07-part1
After=systemd-fsck@/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol047890a35c50b6f07-part1

[Mount]
Where=/var/srv
What=/dev/disk/by-id/nvme-Amazon_Elastic_Block_Store_vol047890a35c50b6f07-part1
Type=xfs

[Install]
RequiredBy=local-fs.target[
```

... which is slightly different than what the FCCT configuration documentation (for 1.0.0) suggests that you manually create.
