### ISSUE TITLE
Key "hostname" and "network" unavailable

### ISSUE THREAD

**Issue by cmonty14** [coreos/fcct#60]
Hi,
I want to generate an ignition file from this FCC file:
```
root@ld3955:/home# more config.yml
variant: fcos
version: 1.0.0

hostname: vm191-fcos

passwd:
  users:
    - name: "core"
      groups: [ sudo, docker ]
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAA [...]

network:
  version: 1
  config:
    - type: physical
      name: eth0
      subnets:
        - type: static
          address: 192.168.100.191/24
          gateway: 192.168.100.11
    - type: nameserver
      address:
        - 8.8.8.8
```

However fcct reports that key "hostname" and "network" are not available.
```
root@ld3955:/home# fcct --input config.yml
warning at $.hostname, line 4 col 1: Unused key hostname
warning at $.network, line 13 col 1: Unused key network
```

Question:
How can I configure a static network in ignition file?

This is required as no DHCP service is available.

THX
