### ISSUE TITLE
Workaround for local file contents

### ISSUE THREAD

**Issue by cfra** [coreos/fcct#83]
I am currently in the process of porting a CoreOS Container Linux Ignition config to Fedora CoreOS 1.0 config.

One major issue I am running into is the following:

In the old setup, the yaml file contains no sensitive content and is tracked publicly, and some sensitive content is pulled in when it is transpiled, using the `local` option of file contents, like following:

```yaml
storage:
  files:
    - path: /root/.ssh/id_rsa
      mode: 0600
      contents:
        local: keys/id_rsa_deployment
```

How can I achieve this with the new config format?

It seems like the `local` option is gone, and the `source` option seems not to apply, as it is only applied when the config is applied, and not during the transpilation process.
