### ISSUE TITLE
Correct way to use `append`

### ISSUE THREAD

**Issue by shivarammysore** [coreos/fcct#85]
What is the correct way to use `append` to a file in YAML

```yaml
  files:
    - path: /etc/sudoers
      overwrite: false
      append: 
        contents:
          inline: core	ALL=(ALL)	NOPASSWD: /usr/bin/docker
```

The above will result in an error with `fcct`:

```text
Error translating config: Error unmarshaling yaml: yaml: line 9: mapping values are not allowed in this context
```

**Comment by bgilbert** [comment]
This should work:
```
variant: fcos
version: 1.0.0
storage:
  files:
    - path: /etc/sudoers
      overwrite: false
      append:
        - inline: |
            core        ALL=(ALL)       NOPASSWD: /usr/bin/docker
```
